    requirementDiagram

    requirement creer_la_signature {
    id: 2.1
    text: the test text.
    risk: high
    verifymethod: test
    }

    requirement editer_les_docs {
    id: 2
    text: blabla
    }

    editer_les_docs - contains -> creer_la_signature